Repository debarshee2004/opensource_guide, pull requests merged in 2024-01, with the labels that each got.

#16 Added Hotstar clone
  projects/apu52_HotstarClone/Images Hotstar/add.png
  projects/apu52_HotstarClone/Images Hotstar/disney.PNG
  projects/apu52_HotstarClone/Images Hotstar/geographic.PNG
  projects/apu52_HotstarClone/Images Hotstar/logo.png
  projects/apu52_HotstarClone/Images Hotstar/marvel.PNG
  projects/apu52_HotstarClone/Images Hotstar/nxt.png
  projects/apu52_HotstarClone/Images Hotstar/pixar.PNG
  projects/apu52_HotstarClone/Images Hotstar/play.png
  projects/apu52_HotstarClone/Images Hotstar/poster 1.png
  projects/apu52_HotstarClone/Images Hotstar/poster 10.png
  projects/apu52_HotstarClone/Images Hotstar/poster 11.png
  projects/apu52_HotstarClone/Images Hotstar/poster 12.png
  projects/apu52_HotstarClone/Images Hotstar/poster 2.png
  projects/apu52_HotstarClone/Images Hotstar/poster 3.png
  projects/apu52_HotstarClone/Images Hotstar/poster 4.png
  projects/apu52_HotstarClone/Images Hotstar/poster 5.png
  projects/apu52_HotstarClone/Images Hotstar/poster 6.png
  projects/apu52_HotstarClone/Images Hotstar/poster 7.png
  projects/apu52_HotstarClone/Images Hotstar/poster 8.png
  projects/apu52_HotstarClone/Images Hotstar/poster 9.png
  projects/apu52_HotstarClone/Images Hotstar/pre.png
  projects/apu52_HotstarClone/Images Hotstar/slider 1.PNG
  projects/apu52_HotstarClone/Images Hotstar/slider 2.PNG
  projects/apu52_HotstarClone/Images Hotstar/slider 3.PNG
  projects/apu52_HotstarClone/Images Hotstar/slider 4.PNG
  projects/apu52_HotstarClone/Images Hotstar/slider 5.PNG
  projects/apu52_HotstarClone/Images Hotstar/star-wars.PNG
  projects/apu52_HotstarClone/Index.html
  projects/apu52_HotstarClone/README.md
  projects/apu52_HotstarClone/Videos Hotstar/disney.mp4
  projects/apu52_HotstarClone/Videos Hotstar/geographic.mp4
  projects/apu52_HotstarClone/Videos Hotstar/marvel.mp4
  projects/apu52_HotstarClone/Videos Hotstar/pixar.mp4
  projects/apu52_HotstarClone/Videos Hotstar/star-war.mp4
  projects/apu52_HotstarClone/index.js
  projects/apu52_HotstarClone/styles.css
Labels: apertre, medium

#17 Added educational website
  projects/apu52_EducationalWebsite/Images/About 3.png
  projects/apu52_EducationalWebsite/Images/Coursera.png
  projects/apu52_EducationalWebsite/Images/Deals 1.svg
  projects/apu52_EducationalWebsite/Images/Deals 2.svg
  projects/apu52_EducationalWebsite/Images/Deals 3.svg
  projects/apu52_EducationalWebsite/Images/Deals 4.svg
  projects/apu52_EducationalWebsite/Images/Digital .png
  projects/apu52_EducationalWebsite/Images/Education.png
  projects/apu52_EducationalWebsite/Images/Elecom.png
  projects/apu52_EducationalWebsite/Images/Fed ex.png
  projects/apu52_EducationalWebsite/Images/Footer Logo.png
  projects/apu52_EducationalWebsite/Images/Front logo.png
  projects/apu52_EducationalWebsite/Images/GFG.png
  projects/apu52_EducationalWebsite/Images/Home Banner 4.png
  projects/apu52_EducationalWebsite/Images/Home banner.png
  projects/apu52_EducationalWebsite/Images/Home bg.svg
  projects/apu52_EducationalWebsite/Images/Indeed.png
  projects/apu52_EducationalWebsite/Images/JS Course 1.png
  projects/apu52_EducationalWebsite/Images/Logo.png
  projects/apu52_EducationalWebsite/Images/Person 1.png
  projects/apu52_EducationalWebsite/Images/Person 3.png
  projects/apu52_EducationalWebsite/Images/Photography.png
  projects/apu52_EducationalWebsite/Images/Shape 1.svg
  projects/apu52_EducationalWebsite/Images/Simplilearn.png
  projects/apu52_EducationalWebsite/Images/UI-UX design.png
  projects/apu52_EducationalWebsite/Images/Video Banner.png
  projects/apu52_EducationalWebsite/Images/Web Dev 2.png
  projects/apu52_EducationalWebsite/Images/about-shape-2.svg
  projects/apu52_EducationalWebsite/Images/about-shape-3.png
  projects/apu52_EducationalWebsite/Images/about-shape-4.svg
  projects/apu52_EducationalWebsite/Images/blog-shape.png
  projects/apu52_EducationalWebsite/Images/hero-shape-2.png
  projects/apu52_EducationalWebsite/Images/motion graphics.png
  projects/apu52_EducationalWebsite/Images/person 2.png
  projects/apu52_EducationalWebsite/Images/udemy.png
  projects/apu52_EducationalWebsite/Images/video-shape-1.png
  projects/apu52_EducationalWebsite/Images/video-shape-2.png
  projects/apu52_EducationalWebsite/README.md
  projects/apu52_EducationalWebsite/index.html
  projects/apu52_EducationalWebsite/main.js
  projects/apu52_EducationalWebsite/style.css
Labels: apertre, medium

#19 issue #15/Random Meme Generator
  LICENSE
  projects/Komal Agarwal_Random Meme Generator/LICENSE
  projects/Komal Agarwal_Random Meme Generator/README.md
  projects/Komal Agarwal_Random Meme Generator/demo.png
  projects/Komal Agarwal_Random Meme Generator/index.html
  projects/Komal Agarwal_Random Meme Generator/logo.jpg
  projects/Komal Agarwal_Random Meme Generator/script.js
  projects/Komal Agarwal_Random Meme Generator/style.css
Labels: apertre, medium

#20 Doc master
  docs/CHAT_GPT.md
  projects/Mohammad Umar Farooq_Calculator/index.html
  projects/Mohammad Umar Farooq_Calculator/script.js
  projects/Mohammad Umar Farooq_Calculator/style.css
  projects/apu52_Scientific Calculator/index.html
  projects/apu52_Scientific Calculator/script.js
  projects/apu52_Scientific Calculator/style.css
Labels: apertre, medium

#29 #5 Travel blog website
  projects/Sneha_blog-Website/Dribbble-Logo.png
  projects/Sneha_blog-Website/README.md
  projects/Sneha_blog-Website/blog.css
  projects/Sneha_blog-Website/blog.html
  projects/Sneha_blog-Website/css.jpeg
  projects/Sneha_blog-Website/facebook.png
  projects/Sneha_blog-Website/favicon.ico
  projects/Sneha_blog-Website/html.png
  projects/Sneha_blog-Website/icon.png
  projects/Sneha_blog-Website/icon2.png
  projects/Sneha_blog-Website/instagram.png
  projects/Sneha_blog-Website/pintrest.png
  projects/Sneha_blog-Website/travel 9.jpg
  projects/Sneha_blog-Website/travel1.jpg
  projects/Sneha_blog-Website/travel10.jpg
  projects/Sneha_blog-Website/travel11.png
  projects/Sneha_blog-Website/travel12.png
  projects/Sneha_blog-Website/travel2.png
  projects/Sneha_blog-Website/travel3.jpg
  projects/Sneha_blog-Website/travel4.jpg
  projects/Sneha_blog-Website/travel5.png
  projects/Sneha_blog-Website/travel6.png
  projects/Sneha_blog-Website/travel7.jpg
  projects/Sneha_blog-Website/travel8.jpg
  projects/Sneha_blog-Website/twitter-icon.webp
Labels: apertre, medium

#33 Drawingapp add using html css js
  projects/SoumojitShome_DrawingApp/index.html
  projects/SoumojitShome_DrawingApp/script.js
  projects/SoumojitShome_DrawingApp/style.css
Labels: enhancement, good first issue, apertre, easy

#32 created chess game using html,css and js
  projects/Satwick_chessGame/Bbishop.png
  projects/Satwick_chessGame/Bking.png
  projects/Satwick_chessGame/Bknight.png
  projects/Satwick_chessGame/Bpawn.png
  projects/Satwick_chessGame/Bqueen.png
  projects/Satwick_chessGame/Brook.png
  projects/Satwick_chessGame/Chess.css
  projects/Satwick_chessGame/Chess.js
  projects/Satwick_chessGame/README.md
  projects/Satwick_chessGame/Wbishop.png
  projects/Satwick_chessGame/Wking.png
  projects/Satwick_chessGame/Wknight.png
  projects/Satwick_chessGame/Wpawn.png
  projects/Satwick_chessGame/Wqueen.png
  projects/Satwick_chessGame/Wrook.png
  projects/Satwick_chessGame/index.html
Labels: enhancement, good first issue, apertre, easy

#35 Bard Module add
  docs/Bard_Module.md
Labels: documentation, apertre, easy

#38 Data processing approches by Rick-03
  docs/Data_processing_approches.md
Labels: documentation, apertre, easy

#40 Google OAuth2.0 Demo Project Done
  projects/ritesh2004_GoogleOAuth2.0Guide/.eslintrc.cjs
  projects/ritesh2004_GoogleOAuth2.0Guide/.gitignore
  projects/ritesh2004_GoogleOAuth2.0Guide/README.md
  projects/ritesh2004_GoogleOAuth2.0Guide/index.html
  projects/ritesh2004_GoogleOAuth2.0Guide/package.json
  projects/ritesh2004_GoogleOAuth2.0Guide/public/vite.svg
  projects/ritesh2004_GoogleOAuth2.0Guide/server/.gitignore
  projects/ritesh2004_GoogleOAuth2.0Guide/server/app.js
  projects/ritesh2004_GoogleOAuth2.0Guide/server/auth.js
  projects/ritesh2004_GoogleOAuth2.0Guide/server/database.js
  projects/ritesh2004_GoogleOAuth2.0Guide/server/model.js
  projects/ritesh2004_GoogleOAuth2.0Guide/server/package.json
  projects/ritesh2004_GoogleOAuth2.0Guide/server/server.js
  projects/ritesh2004_GoogleOAuth2.0Guide/src/App.css
  projects/ritesh2004_GoogleOAuth2.0Guide/src/App.jsx
  projects/ritesh2004_GoogleOAuth2.0Guide/src/assets/react.svg
  projects/ritesh2004_GoogleOAuth2.0Guide/src/context/Authcontext.jsx
  projects/ritesh2004_GoogleOAuth2.0Guide/src/index.css
  projects/ritesh2004_GoogleOAuth2.0Guide/src/main.jsx
  projects/ritesh2004_GoogleOAuth2.0Guide/src/pages/Error.jsx
  projects/ritesh2004_GoogleOAuth2.0Guide/src/pages/Home.jsx
  projects/ritesh2004_GoogleOAuth2.0Guide/src/pages/Profile.jsx
  projects/ritesh2004_GoogleOAuth2.0Guide/src/utilities/Privateroute.jsx
  projects/ritesh2004_GoogleOAuth2.0Guide/vite.config.js
Labels: enhancement, apertre, hard

#41 Update Data_processing_approches.md
  docs/Data_processing_approches.md
Labels: documentation, apertre, easy

#46 ToDoApp Using HTML CSS JS add
  projects/SoumojitShome_Rich_Text_Editor/index.html
  projects/SoumojitShome_Rich_Text_Editor/script.js
  projects/SoumojitShome_Rich_Text_Editor/style.css
  projects/SoumojitShome_ToDo_App/index.html
  projects/SoumojitShome_ToDo_App/script.js
  projects/SoumojitShome_ToDo_App/style.css
Labels: enhancement, apertre, hard

#47 Calculator add
  projects/SoumojitShome_Calculator/level2_task1.html
Labels: enhancement, apertre, easy

#48 admin dashboard using next.js and google auth
  projects/Rick-03_AdminDashboard/.gitignore
  projects/Rick-03_AdminDashboard/README.md
  projects/Rick-03_AdminDashboard/jsconfig.json
  projects/Rick-03_AdminDashboard/next.config.js
  projects/Rick-03_AdminDashboard/package.json
  projects/Rick-03_AdminDashboard/postcss.config.js
  projects/Rick-03_AdminDashboard/public/next.svg
  projects/Rick-03_AdminDashboard/public/vercel.svg
  projects/Rick-03_AdminDashboard/src/app/api/auth/[...nextauth]/route.js
  projects/Rick-03_AdminDashboard/src/app/api/product/add-product/route.js
  projects/Rick-03_AdminDashboard/src/app/api/product/all-products/route.js
  projects/Rick-03_AdminDashboard/src/app/api/user/route.js
  projects/Rick-03_AdminDashboard/src/app/api/visitors/add-visitor/route.js
  projects/Rick-03_AdminDashboard/src/app/api/visitors/all-visitors/route.js
  projects/Rick-03_AdminDashboard/src/app/favicon.ico
  projects/Rick-03_AdminDashboard/src/app/globals.css
  projects/Rick-03_AdminDashboard/src/app/layout.js
  projects/Rick-03_AdminDashboard/src/app/page.js
  projects/Rick-03_AdminDashboard/src/app/products/page.js
  projects/Rick-03_AdminDashboard/src/app/unauth-page/page.js
  projects/Rick-03_AdminDashboard/src/app/visitors/page.js
  projects/Rick-03_AdminDashboard/src/auth-provider/index.js
  projects/Rick-03_AdminDashboard/src/components/DeviceAnalytics/index.js
  projects/Rick-03_AdminDashboard/src/components/FormControls/button.js
  projects/Rick-03_AdminDashboard/src/components/FormControls/input.js
  projects/Rick-03_AdminDashboard/src/components/FormControls/select.js
  projects/Rick-03_AdminDashboard/src/components/Modal/index.js
  projects/Rick-03_AdminDashboard/src/components/Table/index.js
  projects/Rick-03_AdminDashboard/src/components/VisitorsAnalytics/index.js
  projects/Rick-03_AdminDashboard/src/components/YearlyAnalyticsChart/index.js
  projects/Rick-03_AdminDashboard/src/components/card/index.js
  projects/Rick-03_AdminDashboard/src/components/dashboard/index.js
  projects/Rick-03_AdminDashboard/src/components/header/index.js
  projects/Rick-03_AdminDashboard/src/components/products/product-layout.js
  projects/Rick-03_AdminDashboard/src/components/products/product-listing.js
  projects/Rick-03_AdminDashboard/src/components/sidebar/index.js
  projects/Rick-03_AdminDashboard/src/components/visitors/visitors-layout.js
  projects/Rick-03_AdminDashboard/src/components/visitors/visitors-list.js
  projects/Rick-03_AdminDashboard/src/context/index.js
  projects/Rick-03_AdminDashboard/src/database/index.js
  projects/Rick-03_AdminDashboard/src/models/product/index.js
  projects/Rick-03_AdminDashboard/src/models/user/index.js
  projects/Rick-03_AdminDashboard/src/models/visitors/index.js
  projects/Rick-03_AdminDashboard/src/utils/config.js
  projects/Rick-03_AdminDashboard/tailwind.config.js
Labels: enhancement, apertre, hard

#49 Text Editor Add
  projects/SoumojitShome_Text_Editor/.gitignore
  projects/SoumojitShome_Text_Editor/README.md
  projects/SoumojitShome_Text_Editor/package.json
  projects/SoumojitShome_Text_Editor/public/android-icon-144x144.png
  projects/SoumojitShome_Text_Editor/public/android-icon-192x192.png
  projects/SoumojitShome_Text_Editor/public/android-icon-36x36.png
  projects/SoumojitShome_Text_Editor/public/android-icon-48x48.png
  projects/SoumojitShome_Text_Editor/public/android-icon-72x72.png
  projects/SoumojitShome_Text_Editor/public/android-icon-96x96.png
  projects/SoumojitShome_Text_Editor/public/apple-icon-114x114.png
  projects/SoumojitShome_Text_Editor/public/apple-icon-120x120.png
  projects/SoumojitShome_Text_Editor/public/apple-icon-144x144.png
  projects/SoumojitShome_Text_Editor/public/apple-icon-152x152.png
  projects/SoumojitShome_Text_Editor/public/apple-icon-180x180.png
  projects/SoumojitShome_Text_Editor/public/apple-icon-57x57.png
  projects/SoumojitShome_Text_Editor/public/apple-icon-60x60.png
  projects/SoumojitShome_Text_Editor/public/apple-icon-72x72.png
  projects/SoumojitShome_Text_Editor/public/apple-icon-76x76.png
  projects/SoumojitShome_Text_Editor/public/apple-icon-precomposed.png
  projects/SoumojitShome_Text_Editor/public/apple-icon.png
  projects/SoumojitShome_Text_Editor/public/browserconfig.xml
  projects/SoumojitShome_Text_Editor/public/favicon-16x16.png
  projects/SoumojitShome_Text_Editor/public/favicon-32x32.png
  projects/SoumojitShome_Text_Editor/public/favicon-96x96.png
  projects/SoumojitShome_Text_Editor/public/favicon.ico
  projects/SoumojitShome_Text_Editor/public/index.html
  projects/SoumojitShome_Text_Editor/public/manifest.json
  projects/SoumojitShome_Text_Editor/public/ms-icon-144x144.png
  projects/SoumojitShome_Text_Editor/public/ms-icon-150x150.png
  projects/SoumojitShome_Text_Editor/public/ms-icon-310x310.png
  projects/SoumojitShome_Text_Editor/public/ms-icon-70x70.png
  projects/SoumojitShome_Text_Editor/public/robots.txt
  projects/SoumojitShome_Text_Editor/src/App.css
  projects/SoumojitShome_Text_Editor/src/App.js
  projects/SoumojitShome_Text_Editor/src/App.test.js
  projects/SoumojitShome_Text_Editor/src/components/About.js
  projects/SoumojitShome_Text_Editor/src/components/Alert.js
  projects/SoumojitShome_Text_Editor/src/components/Navbar.js
  projects/SoumojitShome_Text_Editor/src/components/TextForm.js
  projects/SoumojitShome_Text_Editor/src/index.css
  projects/SoumojitShome_Text_Editor/src/index.js
  projects/SoumojitShome_Text_Editor/src/logo.svg
  projects/SoumojitShome_Text_Editor/src/reportWebVitals.js
  projects/SoumojitShome_Text_Editor/src/setupTests.js
Labels: enhancement, apertre, hard

#50 Crypto Tracker React project done
  docs/Data_processing_approches.md
  projects/ritesh2004_cryptotracker/.gitignore
  projects/ritesh2004_cryptotracker/README.md
  projects/ritesh2004_cryptotracker/package.json
  projects/ritesh2004_cryptotracker/public/favicon.ico
  projects/ritesh2004_cryptotracker/public/index.html
  projects/ritesh2004_cryptotracker/public/logo192.png
  projects/ritesh2004_cryptotracker/public/logo512.png
  projects/ritesh2004_cryptotracker/public/manifest.json
  projects/ritesh2004_cryptotracker/public/robots.txt
  projects/ritesh2004_cryptotracker/src/App.css
  projects/ritesh2004_cryptotracker/src/App.js
  projects/ritesh2004_cryptotracker/src/Config/api.jsx
  projects/ritesh2004_cryptotracker/src/Config/data.js
  projects/ritesh2004_cryptotracker/src/CryptoContext.jsx
  projects/ritesh2004_cryptotracker/src/components/Banner/Banner.css
  projects/ritesh2004_cryptotracker/src/components/Banner/Banner.jsx
  projects/ritesh2004_cryptotracker/src/components/Carousel.css
  projects/ritesh2004_cryptotracker/src/components/Carousel.jsx
  projects/ritesh2004_cryptotracker/src/components/CoinGraph.css
  projects/ritesh2004_cryptotracker/src/components/CoinGraph.jsx
  projects/ritesh2004_cryptotracker/src/components/CoinTable.jsx
  projects/ritesh2004_cryptotracker/src/components/Header.css
  projects/ritesh2004_cryptotracker/src/components/Header.jsx
  projects/ritesh2004_cryptotracker/src/components/SelectBtn.css
  projects/ritesh2004_cryptotracker/src/components/SelectBtn.jsx
  projects/ritesh2004_cryptotracker/src/components/Table1.css
  projects/ritesh2004_cryptotracker/src/components/banner2.jpg
  projects/ritesh2004_cryptotracker/src/index.css
  projects/ritesh2004_cryptotracker/src/index.js
  projects/ritesh2004_cryptotracker/src/pages/Coinpage.css
  projects/ritesh2004_cryptotracker/src/pages/Coinpage.jsx
  projects/ritesh2004_cryptotracker/src/pages/Homepage.jsx
Labels: enhancement, apertre, hard

#59 currency converter using reactJS
  projects/Rick-03 currencyConverter/.eslintrc.cjs
  projects/Rick-03 currencyConverter/.gitignore
  projects/Rick-03 currencyConverter/README.md
  projects/Rick-03 currencyConverter/index.html
  projects/Rick-03 currencyConverter/package.json
  projects/Rick-03 currencyConverter/postcss.config.js
  projects/Rick-03 currencyConverter/src/App.css
  projects/Rick-03 currencyConverter/src/App.jsx
  projects/Rick-03 currencyConverter/src/components/InputBox.jsx
  projects/Rick-03 currencyConverter/src/components/Text.jsx
  projects/Rick-03 currencyConverter/src/hooks/useCurrencyInfo.js
  projects/Rick-03 currencyConverter/src/index.css
  projects/Rick-03 currencyConverter/src/main.jsx
  projects/Rick-03 currencyConverter/tailwind.config.js
  projects/Rick-03 currencyConverter/vite.config.js
Labels: enhancement, apertre, hard

#58 Coffee Shop Web Add
  projects/SoumojitShome_CoffeeShop_Web/css/owl.carousel.css
  projects/SoumojitShome_CoffeeShop_Web/css/owl.theme.default.min.css
  projects/SoumojitShome_CoffeeShop_Web/css/style.css
  projects/SoumojitShome_CoffeeShop_Web/image/a1.jpg
  projects/SoumojitShome_CoffeeShop_Web/image/a2.jpg
  projects/SoumojitShome_CoffeeShop_Web/image/a3.jpg
  projects/SoumojitShome_CoffeeShop_Web/image/a4.jpg
  projects/SoumojitShome_CoffeeShop_Web/image/a5.jpg
  projects/SoumojitShome_CoffeeShop_Web/image/a6.jpg
  projects/SoumojitShome_CoffeeShop_Web/image/b1.png
  projects/SoumojitShome_CoffeeShop_Web/image/b2.png
  projects/SoumojitShome_CoffeeShop_Web/image/b3.png
  projects/SoumojitShome_CoffeeShop_Web/image/b4.png
  projects/SoumojitShome_CoffeeShop_Web/image/b5.png
  projects/SoumojitShome_CoffeeShop_Web/image/b6.png
  projects/SoumojitShome_CoffeeShop_Web/image/blog1.jpg
  projects/SoumojitShome_CoffeeShop_Web/image/blog2.jpg
  projects/SoumojitShome_CoffeeShop_Web/image/blog3.jpg
  projects/SoumojitShome_CoffeeShop_Web/image/c1.jpg
  projects/SoumojitShome_CoffeeShop_Web/image/c2.jpg
  projects/SoumojitShome_CoffeeShop_Web/image/c3.jpg
  projects/SoumojitShome_CoffeeShop_Web/image/home.jpg
  projects/SoumojitShome_CoffeeShop_Web/image/i1.png
  projects/SoumojitShome_CoffeeShop_Web/image/i2.png
  projects/SoumojitShome_CoffeeShop_Web/image/i3.png
  projects/SoumojitShome_CoffeeShop_Web/image/i4.png
  projects/SoumojitShome_CoffeeShop_Web/image/i5.png
  projects/SoumojitShome_CoffeeShop_Web/image/i6.png
  projects/SoumojitShome_CoffeeShop_Web/image/i7.png
  projects/SoumojitShome_CoffeeShop_Web/image/logo.png
  projects/SoumojitShome_CoffeeShop_Web/image/m1.jpg
  projects/SoumojitShome_CoffeeShop_Web/image/m2.jpg
  projects/SoumojitShome_CoffeeShop_Web/image/m3.jpg
  projects/SoumojitShome_CoffeeShop_Web/image/m4.jpg
  projects/SoumojitShome_CoffeeShop_Web/image/m5.jpg
  projects/SoumojitShome_CoffeeShop_Web/image/m6.jpg
  projects/SoumojitShome_CoffeeShop_Web/image/m7.jpg
  projects/SoumojitShome_CoffeeShop_Web/image/m8.jpg
  projects/SoumojitShome_CoffeeShop_Web/image/o1.jpg
  projects/SoumojitShome_CoffeeShop_Web/image/o2.png
  projects/SoumojitShome_CoffeeShop_Web/image/o3.png
  projects/SoumojitShome_CoffeeShop_Web/image/p1.jpg
  projects/SoumojitShome_CoffeeShop_Web/image/p2.jpg
  projects/SoumojitShome_CoffeeShop_Web/image/p3.jpg
  projects/SoumojitShome_CoffeeShop_Web/image/p4.jpg
  projects/SoumojitShome_CoffeeShop_Web/image/w1.jpg
  projects/SoumojitShome_CoffeeShop_Web/image/w1.png
  projects/SoumojitShome_CoffeeShop_Web/image/w2.jpg
  projects/SoumojitShome_CoffeeShop_Web/index.html
  projects/SoumojitShome_CoffeeShop_Web/js/Jquery3.4.1.min.js
  projects/SoumojitShome_CoffeeShop_Web/js/jquery.js
  projects/SoumojitShome_CoffeeShop_Web/js/owl.carousel.js
  projects/SoumojitShome_CoffeeShop_Web/text
Labels: enhancement, apertre, hard

#73 Tic tac toe using reactjs
  projects/Rick-03_Tictactoe/.gitignore
  projects/Rick-03_Tictactoe/README.md
  projects/Rick-03_Tictactoe/component-diagram.png
  projects/Rick-03_Tictactoe/cover.png
  projects/Rick-03_Tictactoe/package.json
  projects/Rick-03_Tictactoe/public/favicon.ico
  projects/Rick-03_Tictactoe/public/index.html
  projects/Rick-03_Tictactoe/public/logo192.png
  projects/Rick-03_Tictactoe/public/logo512.png
  projects/Rick-03_Tictactoe/public/manifest.json
  projects/Rick-03_Tictactoe/public/robots.txt
  projects/Rick-03_Tictactoe/src/App.css
  projects/Rick-03_Tictactoe/src/App.js
  projects/Rick-03_Tictactoe/src/App.test.js
  projects/Rick-03_Tictactoe/src/components/Board.jsx
  projects/Rick-03_Tictactoe/src/components/GameOver.jsx
  projects/Rick-03_Tictactoe/src/components/GameState.js
  projects/Rick-03_Tictactoe/src/components/Reset.jsx
  projects/Rick-03_Tictactoe/src/components/Strike.jsx
  projects/Rick-03_Tictactoe/src/components/TicTacToe.jsx
  projects/Rick-03_Tictactoe/src/components/Tile.jsx
  projects/Rick-03_Tictactoe/src/index.css
  projects/Rick-03_Tictactoe/src/index.js
  projects/Rick-03_Tictactoe/src/logo.svg
  projects/Rick-03_Tictactoe/src/reportWebVitals.js
  projects/Rick-03_Tictactoe/src/setupTests.js
  projects/Rick-03_Tictactoe/src/sounds/click.wav
  projects/Rick-03_Tictactoe/src/sounds/game_over.wav
Labels: enhancement, apertre, hard

#75 JWT Decoder React App Done
  projects/apu52_TravelWebsite/index.html
  projects/apu52_TravelWebsite/styles.css
  projects/ritesh2004_jwtdecoder/.gitignore
  projects/ritesh2004_jwtdecoder/README.md
  projects/ritesh2004_jwtdecoder/package.json
  projects/ritesh2004_jwtdecoder/public/favicon.ico
  projects/ritesh2004_jwtdecoder/public/index.html
  projects/ritesh2004_jwtdecoder/public/logo192.png
  projects/ritesh2004_jwtdecoder/public/logo512.png
  projects/ritesh2004_jwtdecoder/public/manifest.json
  projects/ritesh2004_jwtdecoder/public/robots.txt
  projects/ritesh2004_jwtdecoder/src/App.js
  projects/ritesh2004_jwtdecoder/src/Footer.jsx
  projects/ritesh2004_jwtdecoder/src/Header.jsx
  projects/ritesh2004_jwtdecoder/src/Page.jsx
  projects/ritesh2004_jwtdecoder/src/index.css
  projects/ritesh2004_jwtdecoder/src/index.js
Labels: enhancement, apertre, hard

#85 #24 SQL Joins
  docs/Google-Gemini-.jpg
  docs/SQL_Joins.md
  docs/Sql joins.jpg
Labels: apertre, easy

#82 Firebase Doc add
  docs/Firebase.md
Labels: documentation, apertre, easy

#89 Taxi booking add
  projects/Taxi_Booking_SoumojitShome/.gitignore
  projects/Taxi_Booking_SoumojitShome/README.md
  projects/Taxi_Booking_SoumojitShome/app/api/search-address/route.tsx
  projects/Taxi_Booking_SoumojitShome/app/favicon.ico
  projects/Taxi_Booking_SoumojitShome/app/globals.css
  projects/Taxi_Booking_SoumojitShome/app/layout.tsx
  projects/Taxi_Booking_SoumojitShome/app/page.tsx
  projects/Taxi_Booking_SoumojitShome/app/sign-in/[[...sign-in]]/page.tsx
  projects/Taxi_Booking_SoumojitShome/app/sign-up/[[...sign-up]]/page.tsx
  projects/Taxi_Booking_SoumojitShome/components/Booking/AutocompleteAddress.tsx
  projects/Taxi_Booking_SoumojitShome/components/Booking/Booking.tsx
  projects/Taxi_Booking_SoumojitShome/components/Booking/Cards.tsx
  projects/Taxi_Booking_SoumojitShome/components/Booking/Cars.tsx
  projects/Taxi_Booking_SoumojitShome/components/Booking/DistanceTime.tsx
  projects/Taxi_Booking_SoumojitShome/components/Map/MapBoxMap.tsx
  projects/Taxi_Booking_SoumojitShome/components/Map/MapBoxRoute.tsx
  projects/Taxi_Booking_SoumojitShome/components/Map/Markers.tsx
  projects/Taxi_Booking_SoumojitShome/components/NavBar.tsx
  projects/Taxi_Booking_SoumojitShome/context/DestinationCordiContext.tsx
  projects/Taxi_Booking_SoumojitShome/context/DirectionDataContext.tsx
  projects/Taxi_Booking_SoumojitShome/context/SourceCordiContext.tsx
  projects/Taxi_Booking_SoumojitShome/context/UserLocationContext.tsx
  projects/Taxi_Booking_SoumojitShome/data/CardsList.tsx
  projects/Taxi_Booking_SoumojitShome/data/CarsList.tsx
  projects/Taxi_Booking_SoumojitShome/middleware.ts
  projects/Taxi_Booking_SoumojitShome/next.config.js
  projects/Taxi_Booking_SoumojitShome/package.json
  projects/Taxi_Booking_SoumojitShome/postcss.config.js
  projects/Taxi_Booking_SoumojitShome/public/0.png
  projects/Taxi_Booking_SoumojitShome/public/1.png
  projects/Taxi_Booking_SoumojitShome/public/11.png
  projects/Taxi_Booking_SoumojitShome/public/2.png
  projects/Taxi_Booking_SoumojitShome/public/22.png
  projects/Taxi_Booking_SoumojitShome/public/3.png
  projects/Taxi_Booking_SoumojitShome/public/33.png
  projects/Taxi_Booking_SoumojitShome/public/4.png
  projects/Taxi_Booking_SoumojitShome/public/44.png
  projects/Taxi_Booking_SoumojitShome/public/5.png
  projects/Taxi_Booking_SoumojitShome/public/55.png
  projects/Taxi_Booking_SoumojitShome/public/apple-pay.png
  projects/Taxi_Booking_SoumojitShome/public/card.png
  projects/Taxi_Booking_SoumojitShome/public/cash.png
  projects/Taxi_Booking_SoumojitShome/public/google-pay.png
  projects/Taxi_Booking_SoumojitShome/public/location.png
  projects/Taxi_Booking_SoumojitShome/public/logo.png
  projects/Taxi_Booking_SoumojitShome/public/next.svg
  projects/Taxi_Booking_SoumojitShome/public/pin.png
  projects/Taxi_Booking_SoumojitShome/public/vercel.svg
  projects/Taxi_Booking_SoumojitShome/public/visa.png
  projects/Taxi_Booking_SoumojitShome/tailwind.config.ts
  projects/Taxi_Booking_SoumojitShome/tsconfig.json
Labels: enhancement, apertre, hard

#92 New Project : Food website
  projects/apu52_FoodWebsite/Images/Butter Masala Dosa.png
  projects/apu52_FoodWebsite/Images/Butter Masala.png
  projects/apu52_FoodWebsite/Images/Chicken Curry.png
  projects/apu52_FoodWebsite/Images/Chicken Manchurian.png
  projects/apu52_FoodWebsite/Images/Chicken Masala.png
  projects/apu52_FoodWebsite/Images/Chicken Roast.png
  projects/apu52_FoodWebsite/Images/Chilli Chicken.png
  projects/apu52_FoodWebsite/Images/Chowmein.png
  projects/apu52_FoodWebsite/Images/Do pyaga.png
  projects/apu52_FoodWebsite/Images/Egg Biriyani.png
  projects/apu52_FoodWebsite/Images/Fried Rice.png
  projects/apu52_FoodWebsite/Images/Goan Fish Biriyani.png
  projects/apu52_FoodWebsite/Images/Handi Chicken.png
  projects/apu52_FoodWebsite/Images/Hyderabadi Biriyani.png
  projects/apu52_FoodWebsite/Images/Hyderabadi Paneer.png
  projects/apu52_FoodWebsite/Images/Idli.png
  projects/apu52_FoodWebsite/Images/Kamrupi Biriyani.png
  projects/apu52_FoodWebsite/Images/Kashmiri Biriyani.png
  projects/apu52_FoodWebsite/Images/Kolkata Biriyani .png
  projects/apu52_FoodWebsite/Images/Logo.png
  projects/apu52_FoodWebsite/Images/Masala Dosa.png
  projects/apu52_FoodWebsite/Images/Matar Paneer.png
  projects/apu52_FoodWebsite/Images/Memoni Biriyani.png
  projects/apu52_FoodWebsite/Images/Momo.png
  projects/apu52_FoodWebsite/Images/Mughlai Biriyani.png
  projects/apu52_FoodWebsite/Images/Murgh Mussalam.png
  projects/apu52_FoodWebsite/Images/Mutton Biriyani.png
  projects/apu52_FoodWebsite/Images/Mysore Bonda.png
  projects/apu52_FoodWebsite/Images/Navaratna Korma.png
  projects/apu52_FoodWebsite/Images/Onion Uttapam.png
  projects/apu52_FoodWebsite/Images/Palak Paneer.png
  projects/apu52_FoodWebsite/Images/Paneer Do pyaga.png
  projects/apu52_FoodWebsite/Images/Paneer Labaddar.png
  projects/apu52_FoodWebsite/Images/Phirni.png
  projects/apu52_FoodWebsite/Images/Plain dosa.png
  projects/apu52_FoodWebsite/Images/Rava Uttapam.png
  projects/apu52_FoodWebsite/Images/Reshmi Kabab.png
  projects/apu52_FoodWebsite/Images/Sambar Bara.png
  projects/apu52_FoodWebsite/Images/Shahi Paneer.png
  projects/apu52_FoodWebsite/Images/Spring Roll.png
  projects/apu52_FoodWebsite/Images/Szceahn Chicken.png
  projects/apu52_FoodWebsite/Images/Veg Biriyani.png
  projects/apu52_FoodWebsite/Images/Veg Curry.png
  projects/apu52_FoodWebsite/Images/Veg Jalfrezzi.png
  projects/apu52_FoodWebsite/Images/Veg Kolahpur.png
  projects/apu52_FoodWebsite/Images/Veg Masala.png
  projects/apu52_FoodWebsite/Images/Veg Pakoda.png
  projects/apu52_FoodWebsite/Images/logo food.png
  projects/apu52_FoodWebsite/README.md
  projects/apu52_FoodWebsite/fooditem.js
  projects/apu52_FoodWebsite/index.html
  projects/apu52_FoodWebsite/index.js
  projects/apu52_FoodWebsite/style.css
Labels: apertre, medium

#90 #21 Gemini_doc
  docs/Gemini_doc.md
  docs/Google-Gemini- (1).jpg
Labels: documentation, apertre, easy

#86 Tetris
  projects/YooAshu_TETRIS/README.md
  projects/YooAshu_TETRIS/Tetris__2019__logo.svg
  projects/YooAshu_TETRIS/clear.WAV
  projects/YooAshu_TETRIS/index.html
  projects/YooAshu_TETRIS/land.mp3
  projects/YooAshu_TETRIS/line.mp3
  projects/YooAshu_TETRIS/move.mp3
  projects/YooAshu_TETRIS/script.js
  projects/YooAshu_TETRIS/style.css
  projects/YooAshu_TETRIS/tetris.mp3
Labels: apertre, medium

#93 Add new Project : Temperature converter
  projects/apu52_TemparatureConverter/README.md
  projects/apu52_TemparatureConverter/Temperature Converter.png
  projects/apu52_TemparatureConverter/index.html
  projects/apu52_TemparatureConverter/main.js
  projects/apu52_TemparatureConverter/style.css
Labels: apertre, medium

#94 URL shortner
  projects/RIck-03_URL-shortner/.eslintrc.cjs
  projects/RIck-03_URL-shortner/.gitignore
  projects/RIck-03_URL-shortner/README.md
  projects/RIck-03_URL-shortner/index.html
  projects/RIck-03_URL-shortner/package.json
  projects/RIck-03_URL-shortner/public/vite.svg
  projects/RIck-03_URL-shortner/src/App.css
  projects/RIck-03_URL-shortner/src/App.jsx
  projects/RIck-03_URL-shortner/src/assets/Firebase.js
  projects/RIck-03_URL-shortner/src/assets/Input.jsx
  projects/RIck-03_URL-shortner/src/assets/react.svg
  projects/RIck-03_URL-shortner/src/index.css
  projects/RIck-03_URL-shortner/src/main.jsx
  projects/RIck-03_URL-shortner/vite.config.js
Labels: apertre, medium

#96 Added password generator and tracker project
  demo/Basic Markdown/learn.md
  demo/Basic Markdown/test.md
  projects/Sangneel_Deb password generator and tracker/main.py
  projects/Sangneel_Deb password generator and tracker/password.png
  projects/Sangneel_Deb password generator and tracker/storefile.json
  projects/Sangneel_Deb password generator and tracker/storefile.txt
  projects/apu52_FoodWebsite/fooditem.js
  projects/apu52_FoodWebsite/index.html
  projects/apu52_FoodWebsite/index.js
  projects/apu52_FoodWebsite/style.css
Labels: enhancement, apertre, hard

#98 weather app using javascript and weather api
  projects/Rick-03_weather-app/README.md
  projects/Rick-03_weather-app/images/clear.png
  projects/Rick-03_weather-app/images/clouds.png
  projects/Rick-03_weather-app/images/drizzle.png
  projects/Rick-03_weather-app/images/haze.png
  projects/Rick-03_weather-app/images/humidity.png
  projects/Rick-03_weather-app/images/mist.png
  projects/Rick-03_weather-app/images/rain.png
  projects/Rick-03_weather-app/images/search.png
  projects/Rick-03_weather-app/images/snow.png
  projects/Rick-03_weather-app/images/wind.png
  projects/Rick-03_weather-app/index.html
  projects/Rick-03_weather-app/script.js
  projects/Rick-03_weather-app/style.css
  projects/apu52_TemparatureConverter/index.html
  projects/apu52_TemparatureConverter/main.js
  projects/apu52_TemparatureConverter/style.css
Labels: apertre, medium
